[workspace]
members = [
    "crates/protos",
    "crates/keys",
    "crates/clock",
    "crates/content",
    "crates/storage",
    "crates/transport",
    "crates/node",
    "crates/tlsutil",
    "crates/netmock",
    "crates/nettor",
    "cmd/bbd",
    "cmd/bbcli",
]
exclude = ["fuzz"]

resolver = "2"
