[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[lib]
name = "storage"
path = "src/lib.rs"

[dependencies]
aes-gcm-siv = "0.11"
clock = { path = "../clock" }
content = { path = "../content" }
hex = "0.4"
keys = { path = "../keys" }
prost = "0.14.3"
protos = { path = "../protos" }
rand = "0.8"
tempfile = "3"
thiserror = "2"
