[package]
name = "bbd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
node = { path = "../../crates/node" }
protos = { path = "../../crates/protos" }
storage = { path = "../../crates/storage" }
tonic = { version = "0.14.2", features = ["transport", "tls-connect-info"] }
futures-util = "0.3"
tokio-stream = { version = "0.1", features = ["net"] }
tokio-rustls = "0.26"
tokio-util = "0.7"
tlsutil = { path = "../../crates/tlsutil" }
dirs = "5"
fs2 = "0.4"
hex = "0.4"
keys = { path = "../../crates/keys" }
nettor = { path = "../../crates/nettor" }
transport = { path = "../../crates/transport" }

[dev-dependencies]
bbcli = { path = "../bbcli" }
netmock = { path = "../../crates/netmock" }
tempfile = "3"
ed25519-dalek = "1"
