[package]
name = "nettor"
version = "0.1.0"
edition = "2021"

[lib]
name = "nettor"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
async-trait = "0.1"
tlsutil = { path = "../tlsutil" }
ed25519-dalek = "1"
hyper-util = { version = "0.1", features = ["tokio"] }
keys = { path = "../keys" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync", "io-util"] }
tracing = "0.1"
arti-client = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared", default-features = false, features = [
    "tokio",
    "onion-service-client",
    "onion-service-service",
    "bridge-client",
    "pt-client",
    "keymgr",
    "experimental-api",
    "rustls",
    "static-sqlite",
    "ephemeral-keystore",
] }
tor-hsservice = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
tor-hscrypto = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
tor-llcrypto = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
tor-cell = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
tor-keymgr = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
tor-config = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
tor-proto = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
tor-rtcompat = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
futures = "0.3"
safelog = "0.8.1"
tokio-rustls = "0.26"
tokio-stream = { version = "0.1", features = ["sync"] }
tonic = { version = "0.14.5", features = ["transport"] }
tower = { version = "0.5", features = ["util"] }
transport = { path = "../transport" }
toml = "1"
tor-config-path = { git = "https://gitlab.torproject.org/starius/arti.git", tag = "arti-v2.2.0-fix-channel-build-task-disappeared" }
