[package]
name = "barterbackup-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
clock = { path = "../crates/clock" }
clitls = { path = "../crates/clitls" }
content = { path = "../crates/content" }
hex = "0.4"
keys = { path = "../crates/keys" }
storage = { path = "../crates/storage" }

[[bin]]
name = "content_decode"
path = "fuzz_targets/content_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "storage_load"
path = "fuzz_targets/storage_load.rs"
test = false
doc = false
bench = false

[[bin]]
name = "certificate_parse"
path = "fuzz_targets/certificate_parse.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
