[package]
name = "nettor"
version = "0.1.0"
edition = "2021"

[lib]
name = "nettor"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tracing = "0.1"
arti-client = { version = "0.34", default-features = false, features = [
    "tokio",
    "onion-service-client",
    "onion-service-service",
    "keymgr",
    "experimental-api",
    "rustls",
    "static-sqlite",
    "ephemeral-keystore",
] }
tor-hsservice = "0.34"
tor-keymgr = "0.34"
tor-config = "0.34"
futures = "0.3"
safelog = "0.5"
