[package]
name = "nettor"
version = "0.1.0"
edition = "2021"

[lib]
name = "nettor"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tracing = "0.1"
arti-client = { version = "0.22", default-features = false, features = ["tokio"] }
tor-hsservice = "0.22"
tor-hscrypto = "0.22"
tor-llcrypto = "0.22"
tor-keymgr = "0.22"
tor-config = "0.22"
futures = "0.3"
tokio-stream = "0.1"
rustls = "0.23"

