[package]
name = "bbd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
node = { path = "../../crates/node" }
protos = { path = "../../crates/protos" }
tonic = { version = "0.14.2", features = ["transport", "tls-connect-info"] }
futures-util = "0.3"
tokio-stream = { version = "0.1", features = ["net"] }
tokio-rustls = "0.26"
clitls = { path = "../../crates/clitls" }
dirs = "5"
 
