// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: bbrpc/barter_backup_server.proto

package bbrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCheckRequest is an empty health check request.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse is an empty health check response.
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_onion is the Tor onion hostname of the caller.
	ClientOnion string `protobuf:"bytes,1,opt,name=client_onion,json=clientOnion,proto3" json:"client_onion,omitempty"`
	// server_onion is the Tor onion hostname of the server.
	ServerOnion   string `protobuf:"bytes,2,opt,name=server_onion,json=serverOnion,proto3" json:"server_onion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetClientOnion() string {
	if x != nil {
		return x.ClientOnion
	}
	return ""
}

func (x *HealthCheckResponse) GetServerOnion() string {
	if x != nil {
		return x.ServerOnion
	}
	return ""
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnionPubkey   []byte                 `protobuf:"bytes,1,opt,name=onion_pubkey,json=onionPubkey,proto3" json:"onion_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{2}
}

func (x *Peer) GetOnionPubkey() []byte {
	if x != nil {
		return x.OnionPubkey
	}
	return nil
}

type PeerExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerExchangeRequest) Reset() {
	*x = PeerExchangeRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerExchangeRequest) ProtoMessage() {}

func (x *PeerExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerExchangeRequest.ProtoReflect.Descriptor instead.
func (*PeerExchangeRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{3}
}

func (x *PeerExchangeRequest) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerExchangeResponse) Reset() {
	*x = PeerExchangeResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerExchangeResponse) ProtoMessage() {}

func (x *PeerExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerExchangeResponse.ProtoReflect.Descriptor instead.
func (*PeerExchangeResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{4}
}

func (x *PeerExchangeResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type ContentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     []byte                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentLength int64                  `protobuf:"varint,2,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentInfo) Reset() {
	*x = ContentInfo{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentInfo) ProtoMessage() {}

func (x *ContentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentInfo.ProtoReflect.Descriptor instead.
func (*ContentInfo) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{5}
}

func (x *ContentInfo) GetContentId() []byte {
	if x != nil {
		return x.ContentId
	}
	return nil
}

func (x *ContentInfo) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type GetContentRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRevisionRequest) Reset() {
	*x = GetContentRevisionRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRevisionRequest) ProtoMessage() {}

func (x *GetContentRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetContentRevisionRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{6}
}

type GetContentRevisionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requester_content is the description of the requester's content stored
	// by the responder, if any.
	RequesterContent *ContentInfo `protobuf:"bytes,1,opt,name=requester_content,json=requesterContent,proto3" json:"requester_content,omitempty"`
	// requester_remaining_seconds is the amount of time the responder will
	// store the content of the requester if the requester does not store the
	// content of the responder.
	RequesterRemainingSeconds int64 `protobuf:"varint,2,opt,name=requester_remaining_seconds,json=requesterRemainingSeconds,proto3" json:"requester_remaining_seconds,omitempty"`
	// responder_content is the description of the responder's content which
	// the requester has to store to fulfill the conditions of the contract.
	// Can be empty if the responder does not store anything at the moment.
	ResponderContent *ContentInfo `protobuf:"bytes,3,opt,name=responder_content,json=responderContent,proto3" json:"responder_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetContentRevisionResponse) Reset() {
	*x = GetContentRevisionResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRevisionResponse) ProtoMessage() {}

func (x *GetContentRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRevisionResponse.ProtoReflect.Descriptor instead.
func (*GetContentRevisionResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetContentRevisionResponse) GetRequesterContent() *ContentInfo {
	if x != nil {
		return x.RequesterContent
	}
	return nil
}

func (x *GetContentRevisionResponse) GetRequesterRemainingSeconds() int64 {
	if x != nil {
		return x.RequesterRemainingSeconds
	}
	return 0
}

func (x *GetContentRevisionResponse) GetResponderContent() *ContentInfo {
	if x != nil {
		return x.ResponderContent
	}
	return nil
}

type SetContentRevisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requester_content is the description of the requester's content which
	// the requester wants the responder to download and store. Can be empty
	// if the requester wants to delete their content.
	// Behavior:
	//   - If requester_content is provided, both content_id and content_length
	//     must be set and content_length must be positive.
	//   - If requester_content is omitted (not set), the responder clears any
	//     previously recorded requester content.
	RequesterContent *ContentInfo `protobuf:"bytes,1,opt,name=requester_content,json=requesterContent,proto3" json:"requester_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetContentRevisionRequest) Reset() {
	*x = SetContentRevisionRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContentRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContentRevisionRequest) ProtoMessage() {}

func (x *SetContentRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContentRevisionRequest.ProtoReflect.Descriptor instead.
func (*SetContentRevisionRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{8}
}

func (x *SetContentRevisionRequest) GetRequesterContent() *ContentInfo {
	if x != nil {
		return x.RequesterContent
	}
	return nil
}

type SetContentRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetContentRevisionResponse) Reset() {
	*x = SetContentRevisionResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContentRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContentRevisionResponse) ProtoMessage() {}

func (x *SetContentRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContentRevisionResponse.ProtoReflect.Descriptor instead.
func (*SetContentRevisionResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{9}
}

type DownloadRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ContentId []byte                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Offset    int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// reference_content_id is an existing revision used in reference
	// sections. Optional.
	ReferenceContentId []byte `protobuf:"bytes,3,opt,name=reference_content_id,json=referenceContentId,proto3" json:"reference_content_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadRequest) GetContentId() []byte {
	if x != nil {
		return x.ContentId
	}
	return nil
}

func (x *DownloadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadRequest) GetReferenceContentId() []byte {
	if x != nil {
		return x.ReferenceContentId
	}
	return nil
}

type RawBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawBytes) Reset() {
	*x = RawBytes{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawBytes) ProtoMessage() {}

func (x *RawBytes) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawBytes.ProtoReflect.Descriptor instead.
func (*RawBytes) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{11}
}

func (x *RawBytes) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Reference struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OffsetInReference int64                  `protobuf:"varint,1,opt,name=offset_in_reference,json=offsetInReference,proto3" json:"offset_in_reference,omitempty"`
	Length            int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{12}
}

func (x *Reference) GetOffsetInReference() int64 {
	if x != nil {
		return x.OffsetInReference
	}
	return 0
}

func (x *Reference) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type DownloadResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TotalLength int64                  `protobuf:"varint,1,opt,name=total_length,json=totalLength,proto3" json:"total_length,omitempty"`
	// sha256 is sha256 hash sum of the file.
	Sha256 []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Types that are valid to be assigned to Section:
	//
	//	*DownloadResponse_RawBytes
	//	*DownloadResponse_Reference
	Section       isDownloadResponse_Section `protobuf_oneof:"section"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadResponse) GetTotalLength() int64 {
	if x != nil {
		return x.TotalLength
	}
	return 0
}

func (x *DownloadResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *DownloadResponse) GetSection() isDownloadResponse_Section {
	if x != nil {
		return x.Section
	}
	return nil
}

func (x *DownloadResponse) GetRawBytes() *RawBytes {
	if x != nil {
		if x, ok := x.Section.(*DownloadResponse_RawBytes); ok {
			return x.RawBytes
		}
	}
	return nil
}

func (x *DownloadResponse) GetReference() *Reference {
	if x != nil {
		if x, ok := x.Section.(*DownloadResponse_Reference); ok {
			return x.Reference
		}
	}
	return nil
}

type isDownloadResponse_Section interface {
	isDownloadResponse_Section()
}

type DownloadResponse_RawBytes struct {
	RawBytes *RawBytes `protobuf:"bytes,3,opt,name=raw_bytes,json=rawBytes,proto3,oneof"`
}

type DownloadResponse_Reference struct {
	Reference *Reference `protobuf:"bytes,4,opt,name=reference,proto3,oneof"`
}

func (*DownloadResponse_RawBytes) isDownloadResponse_Section() {}

func (*DownloadResponse_Reference) isDownloadResponse_Section() {}

var File_bbrpc_barter_backup_server_proto protoreflect.FileDescriptor

const file_bbrpc_barter_backup_server_proto_rawDesc = "" +
	"\n" +
	" bbrpc/barter_backup_server.proto\x12\x05bbrpc\"\x14\n" +
	"\x12HealthCheckRequest\"[\n" +
	"\x13HealthCheckResponse\x12!\n" +
	"\fclient_onion\x18\x01 \x01(\tR\vclientOnion\x12!\n" +
	"\fserver_onion\x18\x02 \x01(\tR\vserverOnion\")\n" +
	"\x04Peer\x12!\n" +
	"\fonion_pubkey\x18\x01 \x01(\fR\vonionPubkey\"8\n" +
	"\x13PeerExchangeRequest\x12!\n" +
	"\x05peers\x18\x01 \x03(\v2\v.bbrpc.PeerR\x05peers\"9\n" +
	"\x14PeerExchangeResponse\x12!\n" +
	"\x05peers\x18\x01 \x03(\v2\v.bbrpc.PeerR\x05peers\"S\n" +
	"\vContentInfo\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\fR\tcontentId\x12%\n" +
	"\x0econtent_length\x18\x02 \x01(\x03R\rcontentLength\"\x1b\n" +
	"\x19GetContentRevisionRequest\"\xde\x01\n" +
	"\x1aGetContentRevisionResponse\x12?\n" +
	"\x11requester_content\x18\x01 \x01(\v2\x12.bbrpc.ContentInfoR\x10requesterContent\x12>\n" +
	"\x1brequester_remaining_seconds\x18\x02 \x01(\x03R\x19requesterRemainingSeconds\x12?\n" +
	"\x11responder_content\x18\x03 \x01(\v2\x12.bbrpc.ContentInfoR\x10responderContent\"\\\n" +
	"\x19SetContentRevisionRequest\x12?\n" +
	"\x11requester_content\x18\x01 \x01(\v2\x12.bbrpc.ContentInfoR\x10requesterContent\"\x1c\n" +
	"\x1aSetContentRevisionResponse\"z\n" +
	"\x0fDownloadRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\fR\tcontentId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x120\n" +
	"\x14reference_content_id\x18\x03 \x01(\fR\x12referenceContentId\" \n" +
	"\bRawBytes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"S\n" +
	"\tReference\x12.\n" +
	"\x13offset_in_reference\x18\x01 \x01(\x03R\x11offsetInReference\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\"\xba\x01\n" +
	"\x10DownloadResponse\x12!\n" +
	"\ftotal_length\x18\x01 \x01(\x03R\vtotalLength\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\x12.\n" +
	"\traw_bytes\x18\x03 \x01(\v2\x0f.bbrpc.RawBytesH\x00R\brawBytes\x120\n" +
	"\treference\x18\x04 \x01(\v2\x10.bbrpc.ReferenceH\x00R\treferenceB\t\n" +
	"\asection2\x96\x03\n" +
	"\x12BarterBackupServer\x12D\n" +
	"\vHealthCheck\x12\x19.bbrpc.HealthCheckRequest\x1a\x1a.bbrpc.HealthCheckResponse\x12G\n" +
	"\fPeerExchange\x12\x1a.bbrpc.PeerExchangeRequest\x1a\x1b.bbrpc.PeerExchangeResponse\x12Y\n" +
	"\x12GetContentRevision\x12 .bbrpc.GetContentRevisionRequest\x1a!.bbrpc.GetContentRevisionResponse\x12Y\n" +
	"\x12SetContentRevision\x12 .bbrpc.SetContentRevisionRequest\x1a!.bbrpc.SetContentRevisionResponse\x12;\n" +
	"\bDownload\x12\x16.bbrpc.DownloadRequest\x1a\x17.bbrpc.DownloadResponseB'Z%github.com/starius/barterbackup/bbrpcb\x06proto3"

var (
	file_bbrpc_barter_backup_server_proto_rawDescOnce sync.Once
	file_bbrpc_barter_backup_server_proto_rawDescData []byte
)

func file_bbrpc_barter_backup_server_proto_rawDescGZIP() []byte {
	file_bbrpc_barter_backup_server_proto_rawDescOnce.Do(func() {
		file_bbrpc_barter_backup_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bbrpc_barter_backup_server_proto_rawDesc), len(file_bbrpc_barter_backup_server_proto_rawDesc)))
	})
	return file_bbrpc_barter_backup_server_proto_rawDescData
}

var file_bbrpc_barter_backup_server_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_bbrpc_barter_backup_server_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),         // 0: bbrpc.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 1: bbrpc.HealthCheckResponse
	(*Peer)(nil),                       // 2: bbrpc.Peer
	(*PeerExchangeRequest)(nil),        // 3: bbrpc.PeerExchangeRequest
	(*PeerExchangeResponse)(nil),       // 4: bbrpc.PeerExchangeResponse
	(*ContentInfo)(nil),                // 5: bbrpc.ContentInfo
	(*GetContentRevisionRequest)(nil),  // 6: bbrpc.GetContentRevisionRequest
	(*GetContentRevisionResponse)(nil), // 7: bbrpc.GetContentRevisionResponse
	(*SetContentRevisionRequest)(nil),  // 8: bbrpc.SetContentRevisionRequest
	(*SetContentRevisionResponse)(nil), // 9: bbrpc.SetContentRevisionResponse
	(*DownloadRequest)(nil),            // 10: bbrpc.DownloadRequest
	(*RawBytes)(nil),                   // 11: bbrpc.RawBytes
	(*Reference)(nil),                  // 12: bbrpc.Reference
	(*DownloadResponse)(nil),           // 13: bbrpc.DownloadResponse
}
var file_bbrpc_barter_backup_server_proto_depIdxs = []int32{
	2,  // 0: bbrpc.PeerExchangeRequest.peers:type_name -> bbrpc.Peer
	2,  // 1: bbrpc.PeerExchangeResponse.peers:type_name -> bbrpc.Peer
	5,  // 2: bbrpc.GetContentRevisionResponse.requester_content:type_name -> bbrpc.ContentInfo
	5,  // 3: bbrpc.GetContentRevisionResponse.responder_content:type_name -> bbrpc.ContentInfo
	5,  // 4: bbrpc.SetContentRevisionRequest.requester_content:type_name -> bbrpc.ContentInfo
	11, // 5: bbrpc.DownloadResponse.raw_bytes:type_name -> bbrpc.RawBytes
	12, // 6: bbrpc.DownloadResponse.reference:type_name -> bbrpc.Reference
	0,  // 7: bbrpc.BarterBackupServer.HealthCheck:input_type -> bbrpc.HealthCheckRequest
	3,  // 8: bbrpc.BarterBackupServer.PeerExchange:input_type -> bbrpc.PeerExchangeRequest
	6,  // 9: bbrpc.BarterBackupServer.GetContentRevision:input_type -> bbrpc.GetContentRevisionRequest
	8,  // 10: bbrpc.BarterBackupServer.SetContentRevision:input_type -> bbrpc.SetContentRevisionRequest
	10, // 11: bbrpc.BarterBackupServer.Download:input_type -> bbrpc.DownloadRequest
	1,  // 12: bbrpc.BarterBackupServer.HealthCheck:output_type -> bbrpc.HealthCheckResponse
	4,  // 13: bbrpc.BarterBackupServer.PeerExchange:output_type -> bbrpc.PeerExchangeResponse
	7,  // 14: bbrpc.BarterBackupServer.GetContentRevision:output_type -> bbrpc.GetContentRevisionResponse
	9,  // 15: bbrpc.BarterBackupServer.SetContentRevision:output_type -> bbrpc.SetContentRevisionResponse
	13, // 16: bbrpc.BarterBackupServer.Download:output_type -> bbrpc.DownloadResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_bbrpc_barter_backup_server_proto_init() }
func file_bbrpc_barter_backup_server_proto_init() {
	if File_bbrpc_barter_backup_server_proto != nil {
		return
	}
	file_bbrpc_barter_backup_server_proto_msgTypes[13].OneofWrappers = []any{
		(*DownloadResponse_RawBytes)(nil),
		(*DownloadResponse_Reference)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bbrpc_barter_backup_server_proto_rawDesc), len(file_bbrpc_barter_backup_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bbrpc_barter_backup_server_proto_goTypes,
		DependencyIndexes: file_bbrpc_barter_backup_server_proto_depIdxs,
		MessageInfos:      file_bbrpc_barter_backup_server_proto_msgTypes,
	}.Build()
	File_bbrpc_barter_backup_server_proto = out.File
	file_bbrpc_barter_backup_server_proto_goTypes = nil
	file_bbrpc_barter_backup_server_proto_depIdxs = nil
}
