// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: bbrpc/barter_backup_server.proto

package bbrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnionPubkey   []byte                 `protobuf:"bytes,1,opt,name=onion_pubkey,json=onionPubkey,proto3" json:"onion_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetOnionPubkey() []byte {
	if x != nil {
		return x.OnionPubkey
	}
	return nil
}

type PeerExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerExchangeRequest) Reset() {
	*x = PeerExchangeRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerExchangeRequest) ProtoMessage() {}

func (x *PeerExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerExchangeRequest.ProtoReflect.Descriptor instead.
func (*PeerExchangeRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{1}
}

func (x *PeerExchangeRequest) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerExchangeResponse) Reset() {
	*x = PeerExchangeResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerExchangeResponse) ProtoMessage() {}

func (x *PeerExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerExchangeResponse.ProtoReflect.Descriptor instead.
func (*PeerExchangeResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{2}
}

func (x *PeerExchangeResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type ContentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     []byte                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentLength int64                  `protobuf:"varint,2,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentInfo) Reset() {
	*x = ContentInfo{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentInfo) ProtoMessage() {}

func (x *ContentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentInfo.ProtoReflect.Descriptor instead.
func (*ContentInfo) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{3}
}

func (x *ContentInfo) GetContentId() []byte {
	if x != nil {
		return x.ContentId
	}
	return nil
}

func (x *ContentInfo) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type GetContentRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRevisionRequest) Reset() {
	*x = GetContentRevisionRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRevisionRequest) ProtoMessage() {}

func (x *GetContentRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetContentRevisionRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{4}
}

type GetContentRevisionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requester_content is the description of the requester's content stored
	// by the responder, if any.
	RequesterContent *ContentInfo `protobuf:"bytes,1,opt,name=requester_content,json=requesterContent,proto3" json:"requester_content,omitempty"`
	// requester_remaining_seconds is the amount of time the responder will
	// store the content of the requester if the requester does not store the
	// content of the responder.
	RequesterRemainingSeconds int64 `protobuf:"varint,2,opt,name=requester_remaining_seconds,json=requesterRemainingSeconds,proto3" json:"requester_remaining_seconds,omitempty"`
	// responder_content is the description of the responder's content which
	// the requester has to store to fulfill the conditions of the contract.
	// Can be empty if the responder does not store anything at the moment.
	ResponderContent *ContentInfo `protobuf:"bytes,3,opt,name=responder_content,json=responderContent,proto3" json:"responder_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetContentRevisionResponse) Reset() {
	*x = GetContentRevisionResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRevisionResponse) ProtoMessage() {}

func (x *GetContentRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRevisionResponse.ProtoReflect.Descriptor instead.
func (*GetContentRevisionResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetContentRevisionResponse) GetRequesterContent() *ContentInfo {
	if x != nil {
		return x.RequesterContent
	}
	return nil
}

func (x *GetContentRevisionResponse) GetRequesterRemainingSeconds() int64 {
	if x != nil {
		return x.RequesterRemainingSeconds
	}
	return 0
}

func (x *GetContentRevisionResponse) GetResponderContent() *ContentInfo {
	if x != nil {
		return x.ResponderContent
	}
	return nil
}

type SetContentRevisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requester_content is the description of the requester's content which
	// the requester wants the responder to download and store. Can be empty
	// if the requester wants to delete their content.
	RequesterContent *ContentInfo `protobuf:"bytes,1,opt,name=requester_content,json=requesterContent,proto3" json:"requester_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetContentRevisionRequest) Reset() {
	*x = SetContentRevisionRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContentRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContentRevisionRequest) ProtoMessage() {}

func (x *SetContentRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContentRevisionRequest.ProtoReflect.Descriptor instead.
func (*SetContentRevisionRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{6}
}

func (x *SetContentRevisionRequest) GetRequesterContent() *ContentInfo {
	if x != nil {
		return x.RequesterContent
	}
	return nil
}

type SetContentRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetContentRevisionResponse) Reset() {
	*x = SetContentRevisionResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContentRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContentRevisionResponse) ProtoMessage() {}

func (x *SetContentRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContentRevisionResponse.ProtoReflect.Descriptor instead.
func (*SetContentRevisionResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{7}
}

type DownloadRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ContentId []byte                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Offset    int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// reference_content_id is an existing revision used in reference
	// sections. Optional.
	ReferenceContentId []byte `protobuf:"bytes,3,opt,name=reference_content_id,json=referenceContentId,proto3" json:"reference_content_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadRequest) GetContentId() []byte {
	if x != nil {
		return x.ContentId
	}
	return nil
}

func (x *DownloadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadRequest) GetReferenceContentId() []byte {
	if x != nil {
		return x.ReferenceContentId
	}
	return nil
}

type RawBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawBytes) Reset() {
	*x = RawBytes{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawBytes) ProtoMessage() {}

func (x *RawBytes) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawBytes.ProtoReflect.Descriptor instead.
func (*RawBytes) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{9}
}

func (x *RawBytes) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Reference struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OffsetInReference int64                  `protobuf:"varint,1,opt,name=offset_in_reference,json=offsetInReference,proto3" json:"offset_in_reference,omitempty"`
	Length            int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{10}
}

func (x *Reference) GetOffsetInReference() int64 {
	if x != nil {
		return x.OffsetInReference
	}
	return 0
}

func (x *Reference) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type DownloadResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TotalLength int64                  `protobuf:"varint,1,opt,name=total_length,json=totalLength,proto3" json:"total_length,omitempty"`
	// sha256 is sha256 hash sum of the file.
	Sha256 []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Types that are valid to be assigned to Section:
	//
	//	*DownloadResponse_RawBytes
	//	*DownloadResponse_Reference
	Section       isDownloadResponse_Section `protobuf_oneof:"section"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadResponse) GetTotalLength() int64 {
	if x != nil {
		return x.TotalLength
	}
	return 0
}

func (x *DownloadResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *DownloadResponse) GetSection() isDownloadResponse_Section {
	if x != nil {
		return x.Section
	}
	return nil
}

func (x *DownloadResponse) GetRawBytes() *RawBytes {
	if x != nil {
		if x, ok := x.Section.(*DownloadResponse_RawBytes); ok {
			return x.RawBytes
		}
	}
	return nil
}

func (x *DownloadResponse) GetReference() *Reference {
	if x != nil {
		if x, ok := x.Section.(*DownloadResponse_Reference); ok {
			return x.Reference
		}
	}
	return nil
}

type isDownloadResponse_Section interface {
	isDownloadResponse_Section()
}

type DownloadResponse_RawBytes struct {
	RawBytes *RawBytes `protobuf:"bytes,3,opt,name=raw_bytes,json=rawBytes,proto3,oneof"`
}

type DownloadResponse_Reference struct {
	Reference *Reference `protobuf:"bytes,4,opt,name=reference,proto3,oneof"`
}

func (*DownloadResponse_RawBytes) isDownloadResponse_Section() {}

func (*DownloadResponse_Reference) isDownloadResponse_Section() {}

type EncryptedDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// encrypted_download_request is AEAD(DownloadRequest).
	EncryptedDownloadRequest []byte `protobuf:"bytes,1,opt,name=encrypted_download_request,json=encryptedDownloadRequest,proto3" json:"encrypted_download_request,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EncryptedDownloadRequest) Reset() {
	*x = EncryptedDownloadRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDownloadRequest) ProtoMessage() {}

func (x *EncryptedDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDownloadRequest.ProtoReflect.Descriptor instead.
func (*EncryptedDownloadRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{12}
}

func (x *EncryptedDownloadRequest) GetEncryptedDownloadRequest() []byte {
	if x != nil {
		return x.EncryptedDownloadRequest
	}
	return nil
}

type EncryptedDownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// encrypted_download_response is AEAD(DownloadResponse).
	EncryptedDownloadResponse []byte `protobuf:"bytes,1,opt,name=encrypted_download_response,json=encryptedDownloadResponse,proto3" json:"encrypted_download_response,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *EncryptedDownloadResponse) Reset() {
	*x = EncryptedDownloadResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDownloadResponse) ProtoMessage() {}

func (x *EncryptedDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDownloadResponse.ProtoReflect.Descriptor instead.
func (*EncryptedDownloadResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{13}
}

func (x *EncryptedDownloadResponse) GetEncryptedDownloadResponse() []byte {
	if x != nil {
		return x.EncryptedDownloadResponse
	}
	return nil
}

type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id is chosen arbitrarily and uniquely identifies a chat session.
	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*ChatRequest_Init
	//	*ChatRequest_Msg
	//	*ChatRequest_File
	//	*ChatRequest_Stop
	Action        isChatRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{14}
}

func (x *ChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatRequest) GetAction() isChatRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ChatRequest) GetInit() *ChatInit {
	if x != nil {
		if x, ok := x.Action.(*ChatRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *ChatRequest) GetMsg() *ChatMessage {
	if x != nil {
		if x, ok := x.Action.(*ChatRequest_Msg); ok {
			return x.Msg
		}
	}
	return nil
}

func (x *ChatRequest) GetFile() *ChatFile {
	if x != nil {
		if x, ok := x.Action.(*ChatRequest_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *ChatRequest) GetStop() *ChatStop {
	if x != nil {
		if x, ok := x.Action.(*ChatRequest_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

type isChatRequest_Action interface {
	isChatRequest_Action()
}

type ChatRequest_Init struct {
	// init is the first action in a chat session. Other chat actions
	// fail until another node makes ChatInit with this chat_id. Each
	// chat_id can be used once in a ChatInit action.
	Init *ChatInit `protobuf:"bytes,2,opt,name=init,proto3,oneof"`
}

type ChatRequest_Msg struct {
	// msg is a regular text message in the chat.
	Msg *ChatMessage `protobuf:"bytes,3,opt,name=msg,proto3,oneof"`
}

type ChatRequest_File struct {
	// file gives the other side the content_id of a local file to
	// download.
	File *ChatFile `protobuf:"bytes,4,opt,name=file,proto3,oneof"`
}

type ChatRequest_Stop struct {
	// stop interrupts a chat. Shutting down the CLI or the daemon
	// closes all chats.
	Stop *ChatStop `protobuf:"bytes,5,opt,name=stop,proto3,oneof"`
}

func (*ChatRequest_Init) isChatRequest_Action() {}

func (*ChatRequest_Msg) isChatRequest_Action() {}

func (*ChatRequest_File) isChatRequest_Action() {}

func (*ChatRequest_Stop) isChatRequest_Action() {}

type ChatInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInit) Reset() {
	*x = ChatInit{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInit) ProtoMessage() {}

func (x *ChatInit) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInit.ProtoReflect.Descriptor instead.
func (*ChatInit) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{15}
}

type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// msg is a text message. Maximum size: 2048 bytes. It must be a valid
	// UTF-8 string with printable terminal characters and no line breaks.
	// It can be encrypted using AEAD if symmetric_encryption is enabled.
	Msg           string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{16}
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ChatFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content_id uniquely identifies a file on the sending side. The file
	// stays available for downloading until this chat is stopped.
	ContentId []byte `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// sha256 is sha256 hash sum of the file.
	Sha256        []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ContentLength int64  `protobuf:"varint,3,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatFile) Reset() {
	*x = ChatFile{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatFile) ProtoMessage() {}

func (x *ChatFile) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatFile.ProtoReflect.Descriptor instead.
func (*ChatFile) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{17}
}

func (x *ChatFile) GetContentId() []byte {
	if x != nil {
		return x.ContentId
	}
	return nil
}

func (x *ChatFile) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ChatFile) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type ChatStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStop) Reset() {
	*x = ChatStop{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStop) ProtoMessage() {}

func (x *ChatStop) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStop.ProtoReflect.Descriptor instead.
func (*ChatStop) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{18}
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{19}
}

type EncryptedChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// encrypted_chat_request is AEAD(ChatRequest).
	EncryptedChatRequest []byte `protobuf:"bytes,1,opt,name=encrypted_chat_request,json=encryptedChatRequest,proto3" json:"encrypted_chat_request,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EncryptedChatRequest) Reset() {
	*x = EncryptedChatRequest{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedChatRequest) ProtoMessage() {}

func (x *EncryptedChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedChatRequest.ProtoReflect.Descriptor instead.
func (*EncryptedChatRequest) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{20}
}

func (x *EncryptedChatRequest) GetEncryptedChatRequest() []byte {
	if x != nil {
		return x.EncryptedChatRequest
	}
	return nil
}

type EncryptedChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// encrypted_chat_response is AEAD(ChatResponse).
	EncryptedChatResponse []byte `protobuf:"bytes,1,opt,name=encrypted_chat_response,json=encryptedChatResponse,proto3" json:"encrypted_chat_response,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EncryptedChatResponse) Reset() {
	*x = EncryptedChatResponse{}
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedChatResponse) ProtoMessage() {}

func (x *EncryptedChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbrpc_barter_backup_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedChatResponse.ProtoReflect.Descriptor instead.
func (*EncryptedChatResponse) Descriptor() ([]byte, []int) {
	return file_bbrpc_barter_backup_server_proto_rawDescGZIP(), []int{21}
}

func (x *EncryptedChatResponse) GetEncryptedChatResponse() []byte {
	if x != nil {
		return x.EncryptedChatResponse
	}
	return nil
}

var File_bbrpc_barter_backup_server_proto protoreflect.FileDescriptor

const file_bbrpc_barter_backup_server_proto_rawDesc = "" +
	"\n" +
	" bbrpc/barter_backup_server.proto\x12\x05bbrpc\")\n" +
	"\x04Peer\x12!\n" +
	"\fonion_pubkey\x18\x01 \x01(\fR\vonionPubkey\"8\n" +
	"\x13PeerExchangeRequest\x12!\n" +
	"\x05peers\x18\x01 \x03(\v2\v.bbrpc.PeerR\x05peers\"9\n" +
	"\x14PeerExchangeResponse\x12!\n" +
	"\x05peers\x18\x01 \x03(\v2\v.bbrpc.PeerR\x05peers\"S\n" +
	"\vContentInfo\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\fR\tcontentId\x12%\n" +
	"\x0econtent_length\x18\x02 \x01(\x03R\rcontentLength\"\x1b\n" +
	"\x19GetContentRevisionRequest\"\xde\x01\n" +
	"\x1aGetContentRevisionResponse\x12?\n" +
	"\x11requester_content\x18\x01 \x01(\v2\x12.bbrpc.ContentInfoR\x10requesterContent\x12>\n" +
	"\x1brequester_remaining_seconds\x18\x02 \x01(\x03R\x19requesterRemainingSeconds\x12?\n" +
	"\x11responder_content\x18\x03 \x01(\v2\x12.bbrpc.ContentInfoR\x10responderContent\"\\\n" +
	"\x19SetContentRevisionRequest\x12?\n" +
	"\x11requester_content\x18\x01 \x01(\v2\x12.bbrpc.ContentInfoR\x10requesterContent\"\x1c\n" +
	"\x1aSetContentRevisionResponse\"z\n" +
	"\x0fDownloadRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\fR\tcontentId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x120\n" +
	"\x14reference_content_id\x18\x03 \x01(\fR\x12referenceContentId\" \n" +
	"\bRawBytes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"S\n" +
	"\tReference\x12.\n" +
	"\x13offset_in_reference\x18\x01 \x01(\x03R\x11offsetInReference\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\"\xba\x01\n" +
	"\x10DownloadResponse\x12!\n" +
	"\ftotal_length\x18\x01 \x01(\x03R\vtotalLength\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\x12.\n" +
	"\traw_bytes\x18\x03 \x01(\v2\x0f.bbrpc.RawBytesH\x00R\brawBytes\x120\n" +
	"\treference\x18\x04 \x01(\v2\x10.bbrpc.ReferenceH\x00R\treferenceB\t\n" +
	"\asection\"X\n" +
	"\x18EncryptedDownloadRequest\x12<\n" +
	"\x1aencrypted_download_request\x18\x01 \x01(\fR\x18encryptedDownloadRequest\"[\n" +
	"\x19EncryptedDownloadResponse\x12>\n" +
	"\x1bencrypted_download_response\x18\x01 \x01(\fR\x19encryptedDownloadResponse\"\xcd\x01\n" +
	"\vChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12%\n" +
	"\x04init\x18\x02 \x01(\v2\x0f.bbrpc.ChatInitH\x00R\x04init\x12&\n" +
	"\x03msg\x18\x03 \x01(\v2\x12.bbrpc.ChatMessageH\x00R\x03msg\x12%\n" +
	"\x04file\x18\x04 \x01(\v2\x0f.bbrpc.ChatFileH\x00R\x04file\x12%\n" +
	"\x04stop\x18\x05 \x01(\v2\x0f.bbrpc.ChatStopH\x00R\x04stopB\b\n" +
	"\x06action\"\n" +
	"\n" +
	"\bChatInit\"\x1f\n" +
	"\vChatMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"h\n" +
	"\bChatFile\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\fR\tcontentId\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\x12%\n" +
	"\x0econtent_length\x18\x03 \x01(\x03R\rcontentLength\"\n" +
	"\n" +
	"\bChatStop\"\x0e\n" +
	"\fChatResponse\"L\n" +
	"\x14EncryptedChatRequest\x124\n" +
	"\x16encrypted_chat_request\x18\x01 \x01(\fR\x14encryptedChatRequest\"O\n" +
	"\x15EncryptedChatResponse\x126\n" +
	"\x17encrypted_chat_response\x18\x01 \x01(\fR\x15encryptedChatResponse2\xa5\x04\n" +
	"\x12BarterBackupServer\x12G\n" +
	"\fPeerExchange\x12\x1a.bbrpc.PeerExchangeRequest\x1a\x1b.bbrpc.PeerExchangeResponse\x12Y\n" +
	"\x12GetContentRevision\x12 .bbrpc.GetContentRevisionRequest\x1a!.bbrpc.GetContentRevisionResponse\x12Y\n" +
	"\x12SetContentRevision\x12 .bbrpc.SetContentRevisionRequest\x1a!.bbrpc.SetContentRevisionResponse\x12;\n" +
	"\bDownload\x12\x16.bbrpc.DownloadRequest\x1a\x17.bbrpc.DownloadResponse\x12V\n" +
	"\x11EncryptedDownload\x12\x1f.bbrpc.EncryptedDownloadRequest\x1a .bbrpc.EncryptedDownloadResponse\x12/\n" +
	"\x04Chat\x12\x12.bbrpc.ChatRequest\x1a\x13.bbrpc.ChatResponse\x12J\n" +
	"\rEncryptedChat\x12\x1b.bbrpc.EncryptedChatRequest\x1a\x1c.bbrpc.EncryptedChatResponseB'Z%github.com/starius/barterbackup/bbrpcb\x06proto3"

var (
	file_bbrpc_barter_backup_server_proto_rawDescOnce sync.Once
	file_bbrpc_barter_backup_server_proto_rawDescData []byte
)

func file_bbrpc_barter_backup_server_proto_rawDescGZIP() []byte {
	file_bbrpc_barter_backup_server_proto_rawDescOnce.Do(func() {
		file_bbrpc_barter_backup_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bbrpc_barter_backup_server_proto_rawDesc), len(file_bbrpc_barter_backup_server_proto_rawDesc)))
	})
	return file_bbrpc_barter_backup_server_proto_rawDescData
}

var file_bbrpc_barter_backup_server_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_bbrpc_barter_backup_server_proto_goTypes = []any{
	(*Peer)(nil),                       // 0: bbrpc.Peer
	(*PeerExchangeRequest)(nil),        // 1: bbrpc.PeerExchangeRequest
	(*PeerExchangeResponse)(nil),       // 2: bbrpc.PeerExchangeResponse
	(*ContentInfo)(nil),                // 3: bbrpc.ContentInfo
	(*GetContentRevisionRequest)(nil),  // 4: bbrpc.GetContentRevisionRequest
	(*GetContentRevisionResponse)(nil), // 5: bbrpc.GetContentRevisionResponse
	(*SetContentRevisionRequest)(nil),  // 6: bbrpc.SetContentRevisionRequest
	(*SetContentRevisionResponse)(nil), // 7: bbrpc.SetContentRevisionResponse
	(*DownloadRequest)(nil),            // 8: bbrpc.DownloadRequest
	(*RawBytes)(nil),                   // 9: bbrpc.RawBytes
	(*Reference)(nil),                  // 10: bbrpc.Reference
	(*DownloadResponse)(nil),           // 11: bbrpc.DownloadResponse
	(*EncryptedDownloadRequest)(nil),   // 12: bbrpc.EncryptedDownloadRequest
	(*EncryptedDownloadResponse)(nil),  // 13: bbrpc.EncryptedDownloadResponse
	(*ChatRequest)(nil),                // 14: bbrpc.ChatRequest
	(*ChatInit)(nil),                   // 15: bbrpc.ChatInit
	(*ChatMessage)(nil),                // 16: bbrpc.ChatMessage
	(*ChatFile)(nil),                   // 17: bbrpc.ChatFile
	(*ChatStop)(nil),                   // 18: bbrpc.ChatStop
	(*ChatResponse)(nil),               // 19: bbrpc.ChatResponse
	(*EncryptedChatRequest)(nil),       // 20: bbrpc.EncryptedChatRequest
	(*EncryptedChatResponse)(nil),      // 21: bbrpc.EncryptedChatResponse
}
var file_bbrpc_barter_backup_server_proto_depIdxs = []int32{
	0,  // 0: bbrpc.PeerExchangeRequest.peers:type_name -> bbrpc.Peer
	0,  // 1: bbrpc.PeerExchangeResponse.peers:type_name -> bbrpc.Peer
	3,  // 2: bbrpc.GetContentRevisionResponse.requester_content:type_name -> bbrpc.ContentInfo
	3,  // 3: bbrpc.GetContentRevisionResponse.responder_content:type_name -> bbrpc.ContentInfo
	3,  // 4: bbrpc.SetContentRevisionRequest.requester_content:type_name -> bbrpc.ContentInfo
	9,  // 5: bbrpc.DownloadResponse.raw_bytes:type_name -> bbrpc.RawBytes
	10, // 6: bbrpc.DownloadResponse.reference:type_name -> bbrpc.Reference
	15, // 7: bbrpc.ChatRequest.init:type_name -> bbrpc.ChatInit
	16, // 8: bbrpc.ChatRequest.msg:type_name -> bbrpc.ChatMessage
	17, // 9: bbrpc.ChatRequest.file:type_name -> bbrpc.ChatFile
	18, // 10: bbrpc.ChatRequest.stop:type_name -> bbrpc.ChatStop
	1,  // 11: bbrpc.BarterBackupServer.PeerExchange:input_type -> bbrpc.PeerExchangeRequest
	4,  // 12: bbrpc.BarterBackupServer.GetContentRevision:input_type -> bbrpc.GetContentRevisionRequest
	6,  // 13: bbrpc.BarterBackupServer.SetContentRevision:input_type -> bbrpc.SetContentRevisionRequest
	8,  // 14: bbrpc.BarterBackupServer.Download:input_type -> bbrpc.DownloadRequest
	12, // 15: bbrpc.BarterBackupServer.EncryptedDownload:input_type -> bbrpc.EncryptedDownloadRequest
	14, // 16: bbrpc.BarterBackupServer.Chat:input_type -> bbrpc.ChatRequest
	20, // 17: bbrpc.BarterBackupServer.EncryptedChat:input_type -> bbrpc.EncryptedChatRequest
	2,  // 18: bbrpc.BarterBackupServer.PeerExchange:output_type -> bbrpc.PeerExchangeResponse
	5,  // 19: bbrpc.BarterBackupServer.GetContentRevision:output_type -> bbrpc.GetContentRevisionResponse
	7,  // 20: bbrpc.BarterBackupServer.SetContentRevision:output_type -> bbrpc.SetContentRevisionResponse
	11, // 21: bbrpc.BarterBackupServer.Download:output_type -> bbrpc.DownloadResponse
	13, // 22: bbrpc.BarterBackupServer.EncryptedDownload:output_type -> bbrpc.EncryptedDownloadResponse
	19, // 23: bbrpc.BarterBackupServer.Chat:output_type -> bbrpc.ChatResponse
	21, // 24: bbrpc.BarterBackupServer.EncryptedChat:output_type -> bbrpc.EncryptedChatResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_bbrpc_barter_backup_server_proto_init() }
func file_bbrpc_barter_backup_server_proto_init() {
	if File_bbrpc_barter_backup_server_proto != nil {
		return
	}
	file_bbrpc_barter_backup_server_proto_msgTypes[11].OneofWrappers = []any{
		(*DownloadResponse_RawBytes)(nil),
		(*DownloadResponse_Reference)(nil),
	}
	file_bbrpc_barter_backup_server_proto_msgTypes[14].OneofWrappers = []any{
		(*ChatRequest_Init)(nil),
		(*ChatRequest_Msg)(nil),
		(*ChatRequest_File)(nil),
		(*ChatRequest_Stop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bbrpc_barter_backup_server_proto_rawDesc), len(file_bbrpc_barter_backup_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bbrpc_barter_backup_server_proto_goTypes,
		DependencyIndexes: file_bbrpc_barter_backup_server_proto_depIdxs,
		MessageInfos:      file_bbrpc_barter_backup_server_proto_msgTypes,
	}.Build()
	File_bbrpc_barter_backup_server_proto = out.File
	file_bbrpc_barter_backup_server_proto_goTypes = nil
	file_bbrpc_barter_backup_server_proto_depIdxs = nil
}
