[package]
name = "bbcli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.11", features = ["transport", "tls"] }
protos = { path = "../../crates/protos" }
clitls = { path = "../../crates/clitls" }
dirs = "5"
rustls = "0.21"
