[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[lib]
name = "protos"
path = "src/lib.rs"

[dependencies]
tonic = { version = "0.11", features = ["transport"] }
prost = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = { version = "0.11", features = ["prost"] }
prost-build = { version = "0.12" }
protoc-bin-vendored = "3"
