.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bbd 1  "bbd " 
.SH NAME
bbd \- BarterBackup daemon
.SH SYNOPSIS
.nf
.B Usage:
Usage: bbd [OPTIONS]
.fi
.SH DESCRIPTION
BarterBackup daemon
.SH OPTIONS
.TP
.B "\-\-local\-addr <LOCAL_ADDR>"
local_addr is the local loopback address for the CLI gRPC service
.RS
env: BBD_LOCAL_ADDR
.RE
.TP
.B "\-\-data\-dir <DATA_DIR>"
data_dir is the base directory for all daemon state
.RS
env: BBD_DATA_DIR
.RE
.TP
.B "\-\-arti\-config <ARTI_CONFIG>"
arti_config is one optional Arti TOML file for custom test networks
.RS
env: BBD_ARTI_CONFIG
.RE
