[package]
name = "netmock"
version = "0.1.0"
edition = "2021"

[lib]
name = "netmock"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
tonic = { version = "0.14.2", features = ["transport"] }
anyhow = "1"
clitls = { path = "../clitls" }
ed25519-dalek = "1"
futures-util = "0.3"
tokio-rustls = "0.26"
tokio-stream = { version = "0.1", features = ["net"] }
